#!/bin/sh
COAUTHOR=`cat ~/.current_pair`
FILE=`cat "$1"`
FIRSTLINE=$(head -n1 $1)

if [ -z "$FIRSTLINE"  ] && [ ! -z "$COAUTHOR" ]; then
    echo "\n\nCo-Authored-By: $COAUTHOR\n$FILE" > "$1"
else
    echo "$FILE" > "$1"
fi

